[general]
show_welcome = false
screenshot_dir = 'I:\Launchbox\Emulators\Xemu\Screenshots'
skip_boot_anim = true

[general.updates]
check = false

[display.quality]
surface_scale = 2

[display.window]
fullscreen_on_startup = true

[sys]
mem_limit = '128'

[sys.files]
bootrom_path = 'I:\Launchbox\Emulators\Xemu\bios\mcpx_1.0.bin'
flashrom_path = 'I:\Launchbox\Emulators\Xemu\bios\Complex_4627.bin'
eeprom_path = 'I:\Launchbox\Emulators\Xemu\bios\eeprom.bin'
hdd_path = 'I:\Launchbox\Emulators\Xemu\hdd\xbox_hdd.qcow2'

